name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: build-results
        path: D:\a\unreal-shimloader\unreal-shimloader

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v5
      with:
        name: build-results
    - name: Display structure of downloaded files
      run: ls -R
